### ISSUE TITLE
FSX Creation Failure

### ISSUE THREAD

**Issue by scorpiontx-awhelan** [aws-solutions-library-samples/aws-batch-arch-for-protein-folding#11]
Hello,
   During initial deployment I left the values empty for the FSX setup so it will generate a new one but it seems to fail out. Any thoughts on the potential solution here?

The following resource(s) failed to create: [FSX].

![image](https://user-images.githubusercontent.com/96496092/236045509-55add58a-9ab1-47d9-b8ff-2c33c813a9d4.png)

**Comment by brianloyal** [comment]
There have been a few times where I've run into an issue with regional capacity limitation for FSx for Lustre that will cause an error like this. Try deleting the stack and deploying it again

**Comment by scorpiontx-awhelan** [comment]
OK, tried a few times. I'll give it another spin in a few hours to see. 

Thank You

**Comment by scorpiontx-awhelan** [comment]
Issue was me not populating the necessary Lustre ports in the security group I created from scratch.
https://docs.aws.amazon.com/fsx/latest/LustreGuide/limit-access-security-groups.html
