### ISSUE TITLE
batchfold_environment.load_latest_root_stack does not paginate through all results

### ISSUE THREAD

**Issue by rwiturralde** [aws-solutions-library-samples/aws-batch-arch-for-protein-folding#13]
I hit this issue specifically with batchfold_environment.load_latest_root_stack, but it's generally true for all places where this repo is calling boto3 client methods that return paginated responses. In the case of load_latest_root_stack, this calls [cloudformation.list_stacks](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation/client/list_stacks.html), which is a paginated call. The current code doesn't paginate the results, so if the root stack isn't in the first page of results then the call won't find the root stack. 

This code should use a [boto3 paginator](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/paginators.html) to paginate through the list_stacks results.

**Comment by brianloyal** [comment]
Resolved with v1.10.1

**Comment by rwiturralde** [comment]
Changes look good - thanks!
