### ISSUE TITLE
S3 error: Access Denied

### ISSUE THREAD

**Issue by kodakmoment** [aws-solutions-library-samples/aws-batch-arch-for-protein-folding#25]
I am getting an S3 Access Denied error when trying to create the CF stack.
It looks like the CF template file is not accessible anymore.

https://aws-batch-architecture-for-alphafold-public-artifacts.s3.us-east-1.amazonaws.com/main/batch-protein-folding-cfn-packaged.yaml

**Comment by brianloyal** [comment]
Thanks for reporting this. I'm looking at it now

**Comment by brianloyal** [comment]
Resolved with v1.12.7
