### ISSUE TITLE
CICD//Quick Launch does not support deploying prior releases. 

### ISSUE THREAD

**Issue by snemir2** [aws-solutions-library-samples/aws-batch-arch-for-protein-folding#7]
https://github.com/aws-solutions-library-samples/aws-batch-arch-for-protein-folding/blob/09501eea58cf22e5d8b661fe052ef3172f6847cc/.gitlab-ci.yml#L100

Launch template link from Readme always point to latest release -- now way to quick-lunch prior tagged versions.   Seemingly, prior templates are not available in S3 .

**Comment by brianloyal** [comment]
Thanks for reaching out! You're correct that there's not currently a way to auto-deploy previous versions of the stack. Can you share more about how this would help you?
