### ISSUE TITLE
Implement support for MMseqs2

### ISSUE THREAD

**Issue by bunher** [aws-solutions-library-samples/aws-batch-arch-for-protein-folding#9]
Would be great to have the option for MMseqs2 as a fast alternative for JackHMMER. See https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb
and 
[Mirdita M, Schütze K, Moriwaki Y, Heo L, Ovchinnikov S, Steinegger M. ColabFold: Making protein folding accessible to all. Nature Methods, 2022](https://www.nature.com/articles/s41592-022-01488-1)

**Comment by brianloyal** [comment]
Thanks for reaching one! We don't have any plans to support MMSeqs2 at this time. Please see #4 for more details
